when:
  event: [push, pull_request]

steps:
  build:
    image: cimg/android:2024.12.1-ndk
    commands:
      - yes | sdkmanager --licenses || true
      - sdkmanager "build-tools;36.0.0" "platforms;android-36"
      - chmod +x gradlew
      - ./gradlew assembleDebug
