steps:
  - name: build
    image: mars.sky.net:8418/lcstyle/flutter-android:21-jdk
    volumes:
      - urlforwarder-gradle:/root/.gradle
    environment:
      ANDROID_SDK_ROOT: /opt/android-sdk
      GRADLE_OPTS: "-Xmx2g -Dorg.gradle.daemon=false"
    commands:
      - chmod +x gradlew
      - ./gradlew assembleDebug
    when:
      - event: [push, manual]
